### ISSUE TITLE
vscode unocss extension not working with nuxt3 (vitesse)

### ISSUE THREAD

**Issue by mwohlan** [unocss/unocss#215]
There is no error message in the developer console. It simply doesn't recognize any classes. Hopefully it's an easy fix.

**Comment by antfu** [comment]
Before the fix is landed, the workaround is to provide `presets` explictly:

```ts
export default {
  buildModules: [
    '@unocss/nuxt'
  ],
  unocss: {
    presets: [
      presetAttributify({ /* preset options */}),
      presetUno(),
    ]
  }
}
```

The root cause is that the Nuxt module does some shortcuts for injecting the presets automatically, but the extension does not handle the resolving logic.

**Comment by antfu** [comment]
Upgrade everything to v0.27.4 should fix this problem.

**Comment by mwohlan** [comment]
@antfu The underlining doesn't work for my in any of my UnoCss Projects ( Both Vue3+Vite and Nuxt 3 ) with 0.27.5

**Comment by antfu** [comment]
> The underlining doesn't work for my in any of my UnoCss Projects ( Both Vue3+Vite and Nuxt 3 ) with 0.27.5

Opps, should fine with v0.27.6 now :P

**Comment by mwohlan** [comment]
@antfu Just a headsup

This works
```js
export default {
  buildModules: [
    '@unocss/nuxt'
  ],
  unocss: {
    presets: [
      presetAttributify({ /* preset options */}),
      presetUno(),
    ]
  }
}
```

This still doesn't work with 28.0 for me. No underlining with this config style. It's not a big problem, but
I don't think its fixed.

```js
  unocss: {
    icons: { scale: 1.0 },
    uno: true,
    webFonts: {
      provider: 'google',
      fonts: {
        mulish: 'Mulish:200,300,400,500,600,700,800,900',
      },
    },
    attributify: true,
    preflight: true,
    shortcuts: [
      ['btn', 'px-4 py-1 rounded inline-block bg-teal-600 text-white cursor-pointer hover:bg-teal-700 disabled:cursor-default disabled:bg-gray-600 disabled:opacity-50'],
    ],
  },
```

**Comment by antfu** [comment]
Oh yeah, the extension does not support grabbing the config from nuxt.config.js yes. Almost forgot
