### ISSUE TITLE
Unable to use Directives mode in files imported by scss

### ISSUE THREAD

**Issue by leosin** [unocss/unocss#2418]
### UnoCSS version

0.50.6

### Describe the bug

I'm using nuxt3

In the file imported by scss, Directives cannot be used. Is there any configuration missing?

### Reproduction

https://stackblitz.com/edit/nuxt-starter-dzo92b?file=app.vue

### System Info

    "@unocss/nuxt": "^0.50.6",
    "nuxt": "^3.3.2",
    "sass": "^1.60.0"

### Validations

- [X] Read the [Contributing Guidelines](https://github.com/unocss/unocss/blob/main/CONTRIBUTING.md).
- [X] Check that there isn't [already an issue](https://github.com/unocss/unocss/issues) that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/unocss/unocss/discussions) or join our [Discord Chat Server](https://chat.antfu.me).
- [X] The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by sibbng** [comment]
This is fixed in https://github.com/unocss/unocss/pull/2338 but not released yet.

**Comment by leosin** [comment]
> This is fixed in #2338 but not released yet.

thank you ! that's awesome

**Comment by sibbng** [comment]
v0.50.7 is released. It should work now.

**Comment by leosin** [comment]
Maybe I didn't describe it clearly
Under normal circumstances, it is no problem to use directives in scss
But for example, when importing other.scss files in main.scss, directives cannot be used in other.scss.

main.scss
```scss
@import './other';

.directives {
  --uno: text-green-500; // work fine
}
```

other.scss
```scss
.sub1 {
  @apply text-orange-500; // not working
}

.sub2 {
  --uno: text-orange-500; // not working
}

.sub3 {
  --at-apply: text-orange-500; // not working
}

.sub4 {
  --uno-apply: text-orange-500; // not working
}
```
This Reproduction has just been updated, you can try it here

https://stackblitz.com/edit/nuxt-starter-dzo92b?file=app.vue

**Comment by sibbng** [comment]
Oh, my bad. I thought you are using postcss plugin. I wonder why you use `enforce: 'pre'` there. It seems working with `enforce: 'default'`.

**Comment by eikaramba** [comment]
this issue is still present. i am not able to use

<style lang="scss">
    .coverage-indicator {
        @apply rounded-t-2xl text-white p-3 md:px-12 -mb-1;
    }
</style>

in a sveltekit +page.svelte file
